### PR TITLE
adding requirements file and updating docs to point to this

### PR DESCRIPTION
**Pull request by TooDissing**
* adding requirements.txt file to address missing dependencies
* updating documentation

### CODE REVIEW

**Comment by TooDissing** [comment]
Hi Filip,

I can see that the build failed with missing files.
Is this a known issue?

If not, please, can you provide me with a hint to two. Then I’ll have a go at addressing it.

**Comment by HeikoGr** [comment]
file check was initiated by me.

The error is caused in the file [euphonium](https://github.com/feelfreelinux/euphonium)/[.github](https://github.com/feelfreelinux/euphonium/tree/master/.github)/[workflows](https://github.com/feelfreelinux/euphonium/tree/master/.github/workflows)/esp-idf.yml on line 63. it’s because the var ${{github.ref_name}} is set to 'euphonium-34/merge' in this merge for pr34.

I have no idea how to fix it properly.

**Comment by feelfreelinux** [comment]
The issue with failed builds in PRs is a separate one. Looks like adding requirements.txt somehow broke the docs / mkdocs pipeline, I'll take a look at it shortly. Everything else seems fine, firmware itself builds just fine too so thanks a lot for the contribution!

**Comment by HeikoGr** [comment]
looks like there is no pip wheel for latest grpcio on alpine linux.

i tried to fix it in PR #35

**Pull request merged**
