### PR TITLE
Docs on adding new plugins

### PR DESCRIPTION
**Pull request by jdthorpe**
These are basically my notes on creating a new plugin that I threw together as I tried to understand the application.  Probably lots of typos and a few errors, but hopefully a good place to start...

### CODE REVIEW

**Comment by jdthorpe** [comment]
- [ ] Importing external components (git repos) should be in line with the [ESP-IDF best practices](https://docs.espressif.com/projects/esp-idf/en/release-v4.2/esp32/api-guides/build-system.html#optional-project-variables) ( e.g. cloning into  PROJECT_DIR/components, or adding submodules to the EXTRA_COMPONENT_DIRS) instead of `add_subdirectory(...)`

- [ ] Probably should at least highlight how the `runTask()` method can be used to manage periodic tasks

**Comment by feelfreelinux** [comment]
Thanks a lot for this! Sorry for late reply - was on vacation for a bit. 
Currently im in process of rewriting the plugins system a little bit - adding packaging, and such, so I decided to wait a bit with exactly describing now its supposed to work. Those notes however, are still really useful :)

**Comment by feelfreelinux** [comment]
I'm really impressed to the extend in which you were able to understand the architecture of this!

**Comment by feelfreelinux** [comment]
Hi, so far - this is an amazing addition :) I'll probably make some edits due to me writing a rewrite of some parts of the system.

Sorry for the long delay, thanks a lot!

**Pull request merged**
